# Generated by Django 6.0.6 on 2026-07-01 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='genre',
            field=models.CharField(choices=[('SF', 'SF'), ('코미디', '코미디'), ('액션', '액션'), ('드라마', '드라마'), ('공포', '공포'), ('로맨스', '로맨스')], max_length=50),
        ),
    ]
